#!/usr/bin/env python3
"""Generate test/test_dock/vectors_generated.h from dock-vectors.json.

The conformance vectors are the shared asset that lets the Light and Prime lanes
be built in parallel and still meet (DOCK-PROTOCOL.md §10). Baking them into a
header keeps the firmware test suite free of JSON parsing and file I/O, so the
whole protocol -- not just the codec -- replays natively against a fake platform.

Emits, per vector: the wire_in bytes, the expected wire_out frames, and the
light_state (files, staged .partials, sd_present, proto_version, clock, the
held-open path) needed to stand up a fake Light in exactly that state.

    python3 tools/gen_vectors.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "dock-vectors.json"
DST = ROOT / "test" / "test_dock" / "vectors_generated.h"


def carr(b: bytes) -> str:
    return "{" + ",".join(f"0x{x:02x}" for x in b) + "}" if b else "{0}"


def main() -> None:
    d = json.loads(SRC.read_text())
    vs = d["vectors"]
    defaults = d["defaults"]["light_state"]

    out = [
        "// GENERATED by tools/gen_vectors.py from dock-vectors.json -- do not edit.",
        f"// vectors_version {d['vectors_version']}, protocol_version {d['protocol_version']}, {len(vs)} vectors.",
        "#ifndef SL_VECTORS_GENERATED_H",
        "#define SL_VECTORS_GENERATED_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct VecFile {",
        "  const char *path;",
        "  const uint8_t *data;",
        "  uint32_t size;",
        "};",
        "",
        "struct VecOut {",
        "  const uint8_t *bytes;",
        "  size_t len;",
        "  uint8_t type;",
        "  uint8_t seq;",
        "};",
        "",
        "struct Vec {",
        "  const char *id;",
        "  const uint8_t *wire_in;",
        "  size_t wire_in_len;",
        "  const VecOut *outs;",
        "  size_t n_outs;",
        "  bool pins;",
        "  // light_state",
        "  const VecFile *files;",
        "  size_t n_files;",
        "  int sd_present;",
        "  int proto_version;",
        "  unsigned long long clock_epoch;",
        "  int clock_quality;",
        "  int clock_set_this_boot;",
        "  int logging_was_active;   // derived from the expected HELLO flags",
        "  const char *open_path;    // held open -> ERR_BUSY; nullptr if none",
        "};",
        "",
    ]

    for i, v in enumerate(vs):
        ls = dict(defaults)
        ls.update(v.get("light_state", {}))

        out.append(f"// [{i}] {v['id']}  ({v['section']})")
        out.append(f"static const uint8_t vin_{i}[] = {carr(bytes.fromhex(v['wire_in']))};")

        for j, e in enumerate(v.get("expect", [])):
            out.append(f"static const uint8_t vout_{i}_{j}[] = {carr(bytes.fromhex(e['wire_out']))};")
        outs = v.get("expect", [])
        if outs:
            rows = []
            for j, e in enumerate(outs):
                w = bytes.fromhex(e["wire_out"])
                rows.append(f"{{vout_{i}_{j}, {len(w)}, 0x{w[1]:02x}, {w[2]}}}")
            out.append(f"static const VecOut vouts_{i}[] = {{{','.join(rows)}}};")

        # --- files on the fake card, plus any pre-staged .partial ---
        files = ls.get("files", {}) or {}
        rows = []
        for k, (path, f) in enumerate(sorted(files.items())):
            content = bytes.fromhex(f["content_hex"]) if "content_hex" in f else b"\x00" * f["size"]
            out.append(f"static const uint8_t vf_{i}_{k}[] = {carr(content)};")
            rows.append(f'{{"{path}", vf_{i}_{k}, {len(content)}}}')

        # 'staged' maps a final path -> how many bytes are already in its .partial.
        # The bytes themselves are the leading N of the committed file's content,
        # which is what a half-finished PUT of that file would actually have left.
        staged = ls.get("staged", {}) or {}
        if isinstance(staged, list):  # tolerate the list form
            staged = {p: defaults["files"][p]["size"] for p in staged}
        for k, (path, nbytes) in enumerate(sorted(staged.items())):
            src = defaults["files"].get(path)
            content = bytes.fromhex(src["content_hex"])[:nbytes] if src else b"\x00" * nbytes
            out.append(f"static const uint8_t vs_{i}_{k}[] = {carr(content)};")
            rows.append(f'{{"{path}.partial", vs_{i}_{k}, {len(content)}}}')

        if rows:
            out.append(f"static const VecFile vfiles_{i}[] = {{{','.join(rows)}}};")
        n_files = len(rows)

        # HELLO's flags bit0 says a capture was running when we docked. The
        # vectors encode it in the expected HELLO payload, so derive it rather
        # than restate it -- one source of truth.
        flags = ls.get("flags", 3)
        was_active = 1 if (flags & 0x01) else 0

        open_path = ls.get("open_path")
        out.append(
            f"static const Vec_init_{i} = 0;" if False else ""
        )
        out.append("")

        v["_gen"] = dict(
            n_files=n_files,
            sd_present=ls.get("sd_present", 1),
            proto_version=ls.get("proto_version", 1),
            clock_epoch=ls.get("clock_epoch", 0),
            clock_quality=ls.get("clock_quality", 0),
            clock_set_this_boot=ls.get("clock_set_this_boot", 0),
            was_active=was_active,
            open_path=open_path,
        )

    out.append("static const Vec VECTORS[] = {")
    for i, v in enumerate(vs):
        g = v["_gen"]
        n = len(v.get("expect", []))
        wi = bytes.fromhex(v["wire_in"])
        op = f'"{g["open_path"]}"' if g["open_path"] else "nullptr"
        out.append(
            f'  {{"{v["id"]}", vin_{i}, {len(wi)}, '
            f'{f"vouts_{i}" if n else "nullptr"}, {n}, '
            f'{"true" if v.get("pins_open_behavior") else "false"}, '
            f'{f"vfiles_{i}" if g["n_files"] else "nullptr"}, {g["n_files"]}, '
            f'{g["sd_present"]}, {g["proto_version"]}, {g["clock_epoch"]}ULL, '
            f'{g["clock_quality"]}, {g["clock_set_this_boot"]}, '
            f'{g["was_active"]}, {op}}},'
        )
    out.append("};")
    out.append(f"static const size_t N_VECTORS = {len(vs)};")
    out.append("")
    out.append("#endif // SL_VECTORS_GENERATED_H")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(l for l in out if l != "") + "\n")
    print(f"wrote {DST.relative_to(ROOT)}: {len(vs)} vectors")


if __name__ == "__main__":
    main()
