#!/usr/bin/env python3
"""Generate test/test_dock/vectors_generated.h from dock-vectors.json.

The conformance vectors are the shared asset that lets the Light and Prime lanes
be built in parallel and still meet (DOCK-PROTOCOL.md §10). Baking them into a
header keeps the firmware test suite free of JSON parsing and file I/O, so the
codec can be exercised natively -- and, if we ever want it, on-device too.

    python3 tools/gen_vectors.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "dock-vectors.json"
DST = ROOT / "test" / "test_dock" / "vectors_generated.h"


def carr(hexstr: str) -> str:
    b = bytes.fromhex(hexstr)
    if not b:
        return "{0}"
    return "{" + ",".join(f"0x{x:02x}" for x in b) + "}"


def main() -> None:
    d = json.loads(SRC.read_text())
    vs = d["vectors"]

    out = [
        "// GENERATED by tools/gen_vectors.py from dock-vectors.json -- do not edit.",
        f"// vectors_version {d['vectors_version']}, protocol_version {d['protocol_version']}, {len(vs)} vectors.",
        "#ifndef SL_VECTORS_GENERATED_H",
        "#define SL_VECTORS_GENERATED_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct VecOut {",
        "  const uint8_t *bytes;",
        "  size_t len;",
        "  uint8_t type;",
        "  uint8_t seq;",
        "};",
        "",
        "struct Vec {",
        "  const char *id;",
        "  const uint8_t *wire_in;",
        "  size_t wire_in_len;",
        "  const VecOut *outs;",
        "  size_t n_outs;",
        "  bool pins;",
        "};",
        "",
    ]

    for i, v in enumerate(vs):
        wi = bytes.fromhex(v["wire_in"])
        out.append(f"// [{i}] {v['id']}  ({v['section']})")
        out.append(f"static const uint8_t vin_{i}[] = {carr(v['wire_in'])};")
        for j, e in enumerate(v.get("expect", [])):
            out.append(f"static const uint8_t vout_{i}_{j}[] = {carr(e['wire_out'])};")
        outs = v.get("expect", [])
        if outs:
            rows = []
            for j, e in enumerate(outs):
                w = bytes.fromhex(e["wire_out"])
                rows.append(f"{{vout_{i}_{j}, {len(w)}, 0x{w[1]:02x}, {w[2]}}}")
            out.append(f"static const VecOut vouts_{i}[] = {{{','.join(rows)}}};")
        else:
            out.append(f"static const VecOut *vouts_{i} = nullptr;")
        out.append("")

    out.append("static const Vec VECTORS[] = {")
    for i, v in enumerate(vs):
        wi = bytes.fromhex(v["wire_in"])
        n = len(v.get("expect", []))
        pins = "true" if v.get("pins_open_behavior") else "false"
        outs_ref = f"vouts_{i}" if n else "nullptr"
        out.append(
            f'  {{"{v["id"]}", vin_{i}, {len(wi)}, {outs_ref}, {n}, {pins}}},'
        )
    out.append("};")
    out.append(f"static const size_t N_VECTORS = {len(vs)};")
    out.append("")
    out.append("#endif // SL_VECTORS_GENERATED_H")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(out) + "\n")
    print(f"wrote {DST.relative_to(ROOT)}: {len(vs)} vectors")


if __name__ == "__main__":
    main()
